### ISSUE TITLE
Handykamera

### ISSUE THREAD

**Issue by MyNameIsMaMi** [GhostLegionRP/Betatest#113]
Die Handykamera fotografiert in 3rd Person. Wenn man am ausbluten ist kann man das Handy normal benutzen.

**Comment by GhostLegionRP** [comment]
Die Handykamera fotografiert in 3rd Person.  -> Kamera kann umgestellt werden.
Ausbluten ist der Spielmechanik geschuldet -> derzeit keine lösung vorhanden-.
