### ISSUE TITLE
Lieferdienst an den Docks

### ISSUE THREAD

**Issue by Pfoenix997** [GhostLegionRP/Betatest#117]
Sobald ich zum markierten Punkt fahre, lässt sich weder auf ALT noch auf den roten Blip interagieren.

**Comment by SaschaB88** [comment]
Hast du mit E ein Paket aus dem Auto genommen und mit E am roten Blip abgegeben ? 
Habs extra gerade nochmal getestet und läuft ;) hab auch ein Video für dich ^^
