### ISSUE TITLE
Pawnshop

### ISSUE THREAD

**Issue by SaschaB88** [GhostLegionRP/Betatest#42]
Beim betreten des Pawnshops bei 7075 wird der Text "Verkaufsstelle angezeigt, wenn man dann E drückt kommt ein Händlerinventar, aber nur beim 1. mal. Goldketten und Rolex, lassen sich auf jeden fall nicht im Traphouse oder beim Pawnshop abgeben.

Eve

**Comment by GhostLegionRP** [comment]
EDIT: Im Pawnshop kann man jetzt verkaufen, aber es wird nicht angezeigt was man dafür an GEld bekommt.
