### ISSUE TITLE
Feldfrüchte

### ISSUE THREAD

**Issue by SaschaB88** [GhostLegionRP/Betatest#50]
Die Anzeige verbessern, wo welche Feldfrüchte geerntet werden können (Chili, Tomaten, grüne Paprika) vielleicht auch Sortieren von den Erntepunkten her.
Sojabohnen sollen wo sein?

**Comment by GhostLegionRP** [comment]
Target Punkte umbenannt, Blips heißen gleich, da die Gärten mehrere Arten ausgeben können.
