### ISSUE TITLE
Schwarzgeld im Inventar stapelt sich nicht

### ISSUE THREAD

**Issue by DGreisi** [GhostLegionRP/Betatest#61]
von jeder Kasse bekommt man X Schwarzgeld, es bleibt aber immer X Schwarzgeld und man bekommt immer neue Stapel in die Tasche, welche man nicht summieren kann

**Comment by SaschaB88** [comment]
Ist bekannt, habe ich gestern mit Sven drüber gesprochen, wird Stackbar gemacht
