### ISSUE TITLE
Koks Dupe

### ISSUE THREAD

**Issue by SaschaB88** [GhostLegionRP/Betatest#69]
Wenn man die Mission abschließt (Flugzeug zurück bringt) konnte ich 1KG Koks dupen, indem ich das Inventar  öffnete, mit Rechtsklick das Koks auf den Boden legte und das Inventar wieder schloss. Als ich das Koks nehmen wollte, fiel mir auf das ich noch 1KG im Inventar hatte. Somit aus 1 mach 2.

**Comment by GhostLegionRP** [comment]
Kein Bug du warst nur schneller als das System 2 Bricks sind immer wo du bekommst
